### PR TITLE
fix(Hero Section): buttons and image positions

### PR DESCRIPTION
**Pull request by khatri7**
Also updated the breakpoint values to 1240, 1024, 768

### CODE REVIEW

**Comment by Oceaneyes123** [comment]
@khatri7 , you can link it on another issue, 

you can create your own

**Comment by khatri7** [comment]
I have linked it to the 2 issues I fixed in this @Oceaneyes123 @Zack-Dx

**Comment by Zack-Dx** [comment]
@khatri7 its breaking the mobile hamburger responsiveness. Please check!

**Comment by khatri7** [comment]
will fix this

**Pull request closed without merging**
